// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecqiimdlcbrltktzkgax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjcWlpbWRsY2JybHRrdHprZ2F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0Njc3ODYsImV4cCI6MjA1ODA0Mzc4Nn0.VgSqCK0oTAY1_LIxu-Kg9qq9j2aae_MBnLeps0lhC0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);